name: Check Rust build
on:
  pull_request:
  push:
    paths:
        - ".github/**"
        - "pna_wasm/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build Image
      run: npm run build:image

    - name: Build WebAssembly
      run: npm run build:wasm

    - name: Run WebAssembly tests
      run: npm run test:wasm

  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Check code format
      working-directory: pna_wasm
      run: cargo fmt --check
